name: bunkr
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_secure_storage: ^9.0.0
  dio: ^5.7.0
  google_fonts: ^6.0.0
  intl: ^0.18.1
  flutter_svg: ^2.1.0
  badges: ^3.0.0
  provider: ^6.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - lib/assets/avatars/male_1.png
    - lib/assets/avatars/male_2.png
    - lib/assets/avatars/male_3.png
    - lib/assets/avatars/male_4.png
    - lib/assets/avatars/male_5.png
    - lib/assets/avatars/male_6.png
    - lib/assets/avatars/female_1.png
    - lib/assets/avatars/female_2.png
    - lib/assets/avatars/female_3.png
    - lib/assets/avatars/female_4.png
    - lib/assets/avatars/female_5.png
    - lib/assets/avatars/female_6.png
    - lib/assets/avatars/user.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"
